INSERT INTO department (name) VALUES ("SALES");
INSERT INTO department (name) VALUES ("ACCOUNTING");
INSERT INTO department (name) VALUES ("PARTYPLANNING");
INSERT INTO role (title, salary, department_id) VALUES ("SALESPERSON", "$55,000 + 5% of sales", 1);
INSERT INTO role (title, salary, department_id) VALUES ("ACCOUNTANT", "$70,000", 2);
INSERT INTO role (title, salary, department_id) VALUES ("PARTYPLANNER", "$300,000 + 20% of sales", 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('JIM', 'HALPERT', 1, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('DWIGHT', 'SCHRUTE', 1, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('OSCAR', 'MARTINEZ', 2, 2);
INSERT INTO employee (first_name, last_name, role_id) VALUES ('PHYLLIS', 'VANCE', 3);